/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M4
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The dependencies that this property has on other properties
type PropertyDependency struct {
	// The name of the property that is depended upon
	PropertyName string `json:"propertyName,omitempty"`
	// The name of the property that is depended upon
	PropertyDisplayName string `json:"propertyDisplayName,omitempty"`
	// The values that satisfy the dependency
	DependentValues []string `json:"dependentValues,omitempty"`
}
