/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.6.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// Indicates that this property is for selecting a controller service of the specified type
type DefinedType struct {
	// The artifact name of the bundle that provides the referenced type.
	Artifact string `json:"artifact,omitempty"`
	// The group name of the bundle that provides the referenced type.
	Group string `json:"group,omitempty"`
	// The fully-qualified class type
	Type_ string `json:"type,omitempty"`
	// The description of the type.
	TypeDescription string `json:"typeDescription,omitempty"`
	// The version of the bundle that provides the referenced type.
	Version string `json:"version,omitempty"`
}
