/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.5.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The NodeStatusSnapshotsDTO objects that provide the actual metric values for the component, for each node. If the NiFi instance is not clustered, this value will be null.
type NodeStatusSnapshotsDto struct {
	// The node's host/ip address.
	Address string `json:"address,omitempty"`
	// The port the node is listening for API requests.
	ApiPort int32 `json:"apiPort,omitempty"`
	// The id of the node.
	NodeId string `json:"nodeId,omitempty"`
	// A list of StatusSnapshotDTO objects that provide the actual metric values for the component for this node.
	StatusSnapshots []StatusSnapshotDto `json:"statusSnapshots,omitempty"`
}
