/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.9.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The Connector DTO
type ConnectorDto struct {
	ActiveConfiguration *ConnectorConfigurationDto `json:"activeConfiguration,omitempty"`
	// The available actions that can be performed on this Connector.
	AvailableActions []ConnectorActionDto `json:"availableActions,omitempty"`
	Bundle *BundleDto `json:"bundle,omitempty"`
	// The URL for this connector's configuration/wizard custom UI, if applicable.
	ConfigurationUrl string `json:"configurationUrl,omitempty"`
	// The URL for this connector's details custom UI, if applicable.
	DetailsUrl string `json:"detailsUrl,omitempty"`
	// Whether the extension for this connector is missing.
	ExtensionMissing bool `json:"extensionMissing,omitempty"`
	// The id of the component.
	Id string `json:"id,omitempty"`
	// The identifier of the root Process Group managed by this Connector.
	ManagedProcessGroupId string `json:"managedProcessGroupId,omitempty"`
	// Whether multiple versions of this connector are available.
	MultipleVersionsAvailable bool `json:"multipleVersionsAvailable,omitempty"`
	// The name of the Connector.
	Name string `json:"name,omitempty"`
	// The id of parent process group of this component if applicable.
	ParentGroupId string `json:"parentGroupId,omitempty"`
	Position *PositionDto `json:"position,omitempty"`
	// The state of the Connector.
	State string `json:"state,omitempty"`
	// The fully qualified type of the Connector.
	Type_ string `json:"type,omitempty"`
	// The validation errors for the connector.
	ValidationErrors []string `json:"validationErrors,omitempty"`
	// Indicates whether the Connector is valid, invalid, or still in the process of validating
	ValidationStatus string `json:"validationStatus,omitempty"`
	// The ID of the corresponding component that is under version control
	VersionedComponentId string `json:"versionedComponentId,omitempty"`
	WorkingConfiguration *ConnectorConfigurationDto `json:"workingConfiguration,omitempty"`
}
