/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The status of all provided parameters for this parameter provider
type ParameterStatusDto struct {
	Parameter *ParameterEntity `json:"parameter,omitempty"`
	// Indicates the status of the parameter, compared to the existing parameter context
	Status string `json:"status,omitempty"`
}
