/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.1.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The reporting tasks
type VersionedReportingTask struct {
	// The annotation for the reporting task. This is how the custom UI relays configuration to the reporting task.
	AnnotationData string `json:"annotationData,omitempty"`
	Bundle *Bundle `json:"bundle,omitempty"`
	// The user-supplied comments for the component
	Comments string `json:"comments,omitempty"`
	ComponentType string `json:"componentType,omitempty"`
	// The ID of the Process Group that this component belongs to
	GroupIdentifier string `json:"groupIdentifier,omitempty"`
	// The component's unique identifier
	Identifier string `json:"identifier,omitempty"`
	// The instance ID of an existing component that is described by this VersionedComponent, or null if this is not mapped to an instantiated component
	InstanceIdentifier string `json:"instanceIdentifier,omitempty"`
	// The component's name
	Name string `json:"name,omitempty"`
	Position *Position `json:"position,omitempty"`
	// The properties for the component. Properties whose value is not set will only contain the property name.
	Properties map[string]string `json:"properties,omitempty"`
	// The property descriptors for the component.
	PropertyDescriptors map[string]VersionedPropertyDescriptor `json:"propertyDescriptors,omitempty"`
	// Indicates the scheduled state for the Reporting Task
	ScheduledState string `json:"scheduledState,omitempty"`
	// The frequency with which to schedule the reporting task. The format of the value will depend on the value of schedulingStrategy.
	SchedulingPeriod string `json:"schedulingPeriod,omitempty"`
	// Indicates scheduling strategy that should dictate how the reporting task is triggered.
	SchedulingStrategy string `json:"schedulingStrategy,omitempty"`
	// The type of the extension component
	Type_ string `json:"type,omitempty"`
}
