/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.6.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// A list of dependencies that must be met in order for this Property to be relevant. If any of these dependencies is not met, the property described by this Property Descriptor is not relevant.
type PropertyDependencyDto struct {
	// The values for the property that satisfies the dependency, or null if the dependency is satisfied by the presence of any value for the associated property name
	DependentValues []string `json:"dependentValues,omitempty"`
	// The name of the property that is being depended upon
	PropertyName string `json:"propertyName,omitempty"`
}
