/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.6.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The required permission necessary for this restriction.
type RequiredPermissionDto struct {
	// The required sub-permission necessary for this restriction.
	Id string `json:"id,omitempty"`
	// The label for the required sub-permission necessary for this restriction.
	Label string `json:"label,omitempty"`
}
