/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type ParameterProviderReference struct {
	// The identifier of the parameter provider
	Identifier string `json:"identifier,omitempty"`
	// The name of the parameter provider
	Name string `json:"name,omitempty"`
	// The fully qualified name of the parameter provider class.
	Type_ string `json:"type,omitempty"`
	Bundle *Bundle `json:"bundle,omitempty"`
}
