/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.4.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The Update Request
type ParameterContextUpdateRequestDto struct {
	// Whether or not the request is completed
	Complete bool `json:"complete,omitempty"`
	// The reason for the request failing, or null if the request has not failed
	FailureReason string `json:"failureReason,omitempty"`
	// The timestamp of when the request was last updated
	LastUpdated      string               `json:"lastUpdated,omitempty"`
	ParameterContext *ParameterContextDto `json:"parameterContext,omitempty"`
	// A value between 0 and 100 (inclusive) indicating how close the request is to completion
	PercentCompleted int32 `json:"percentCompleted,omitempty"`
	// The components that are referenced by the update.
	ReferencingComponents []AffectedComponentEntity `json:"referencingComponents,omitempty"`
	// The ID of the request
	RequestId string `json:"requestId,omitempty"`
	// A description of the current state of the request
	State string `json:"state,omitempty"`
	// The timestamp of when the request was submitted
	SubmissionTime string `json:"submissionTime,omitempty"`
	// The steps that are required in order to complete the request, along with the status of each
	UpdateSteps []ParameterContextUpdateStepDto `json:"updateSteps,omitempty"`
	// The URI for the request
	Uri string `json:"uri,omitempty"`
}
