/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.9.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The state entries for a single node
type VersionedNodeState struct {
	// The state key-value pairs for this node
	State map[string]string `json:"state,omitempty"`
}
