/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.4.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// If the processor supports dynamic relationships, this describes the dynamic relationship
type DynamicRelationship struct {
	// The description of the dynamic relationship
	Description string `json:"description,omitempty"`
	// The description of the dynamic relationship name
	Name string `json:"name,omitempty"`
}
