/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.6.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The coordinate of another NAR that the this NAR is dependent on, or null if not dependent on another NAR.
type NarCoordinateDto struct {
	// The artifact id of the NAR.
	Artifact string `json:"artifact,omitempty"`
	// The group of the NAR.
	Group string `json:"group,omitempty"`
	// The version of the NAR.
	Version string `json:"version,omitempty"`
}
