/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.6.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type ConnectionStatusEntity struct {
	// Indicates whether the user can read a given resource.
	CanRead bool `json:"canRead,omitempty"`
	ConnectionStatus *ConnectionStatusDto `json:"connectionStatus,omitempty"`
}
