/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.6.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type NodeDto struct {
	// The active threads for the NiFi on the node.
	ActiveThreadCount int32 `json:"activeThreadCount,omitempty"`
	// The node's host/ip address.
	Address string `json:"address,omitempty"`
	// The port the node is listening for API requests.
	ApiPort int32 `json:"apiPort,omitempty"`
	// The total size of all FlowFiles that are queued up on the node
	BytesQueued int64 `json:"bytesQueued,omitempty"`
	// The time of the node's last connection request.
	ConnectionRequested string `json:"connectionRequested,omitempty"`
	// The node's events.
	Events []NodeEventDto `json:"events,omitempty"`
	FlowFileBytes int64 `json:"flowFileBytes,omitempty"`
	// The number of FlowFiles that are queued up on the node
	FlowFilesQueued int32 `json:"flowFilesQueued,omitempty"`
	// the time of the nodes's last heartbeat.
	Heartbeat string `json:"heartbeat,omitempty"`
	// The id of the node.
	NodeId string `json:"nodeId,omitempty"`
	// The time at which this Node was last refreshed.
	NodeStartTime string `json:"nodeStartTime,omitempty"`
	// The queue the NiFi on the node.
	Queued string `json:"queued,omitempty"`
	// The roles of this node.
	Roles []string `json:"roles,omitempty"`
	// The node's status.
	Status string `json:"status,omitempty"`
}
