/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type AccessConfigurationDto struct {
	// Indicates whether or not this NiFi supports user login.
	SupportsLogin bool `json:"supportsLogin,omitempty"`
}
