/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type ProcessorRunStatusDetailsEntity struct {
	Revision *RevisionDto `json:"revision,omitempty"`
	Permissions *PermissionsDto `json:"permissions,omitempty"`
	RunStatusDetails *ProcessorRunStatusDetailsDto `json:"runStatusDetails,omitempty"`
}
