/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.3.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type DimensionsDto struct {
	// The height of the label in pixels when at a 1:1 scale.
	Height float64 `json:"height,omitempty"`
	// The width of the label in pixels when at a 1:1 scale.
	Width float64 `json:"width,omitempty"`
}
