/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type RegisteredFlow struct {
	Identifier string `json:"identifier,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Branch string `json:"branch,omitempty"`
	BucketIdentifier string `json:"bucketIdentifier,omitempty"`
	BucketName string `json:"bucketName,omitempty"`
	CreatedTimestamp int64 `json:"createdTimestamp,omitempty"`
	LastModifiedTimestamp int64 `json:"lastModifiedTimestamp,omitempty"`
	Permissions *FlowRegistryPermissions `json:"permissions,omitempty"`
	VersionCount int64 `json:"versionCount,omitempty"`
	VersionInfo *RegisteredFlowVersionInfo `json:"versionInfo,omitempty"`
}
