/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The coordinates where the remote flow is stored, or null if the Process Group is not directly under Version Control
type VersionedFlowCoordinates struct {
	// The identifier of the Flow Registry that contains the flow
	RegistryId string `json:"registryId,omitempty"`
	// The location of the Flow Registry that stores the flow
	StorageLocation string `json:"storageLocation,omitempty"`
	// The UUID of the bucket that the flow resides in
	BucketId string `json:"bucketId,omitempty"`
	// The UUID of the flow
	FlowId string `json:"flowId,omitempty"`
	// The version of the flow
	Version int32 `json:"version,omitempty"`
	// Whether or not these coordinates point to the latest version of the flow
	Latest bool `json:"latest,omitempty"`
}
