/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.3.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type BannerDto struct {
	// The footer text.
	FooterText string `json:"footerText,omitempty"`
	// The header text.
	HeaderText string `json:"headerText,omitempty"`
}
