/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.8.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type ClearBulletinsRequestEntity struct {
	// The timestamp from which to clear bulletins (inclusive). This field is required.
	FromTimestamp string `json:"fromTimestamp"`
}
