/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.4.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The steps that are required in order to complete the request, along with the status of each
type ParameterContextUpdateStepDto struct {
	// Whether or not this step has completed
	Complete bool `json:"complete,omitempty"`
	// Explanation of what happens in this step
	Description string `json:"description,omitempty"`
	// An explanation of why this step failed, or null if this step did not fail
	FailureReason string `json:"failureReason,omitempty"`
}
