/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.4.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// Descriptions of configuration properties applicable to this component.
type PropertyDescriptor struct {
	// A list of the allowable values for the property
	AllowableValues []PropertyAllowableValue `json:"allowableValues,omitempty"`
	// The default value if a user-set value is not specified
	DefaultValue string `json:"defaultValue,omitempty"`
	// The dependencies that this property has on other properties
	Dependencies []PropertyDependency `json:"dependencies,omitempty"`
	// The description of what the property does
	Description string `json:"description,omitempty"`
	// The display name of the property key, if different from the name
	DisplayName string `json:"displayName,omitempty"`
	// Whether or not the descriptor is for a dynamically added property
	Dynamic bool `json:"dynamic,omitempty"`
	// The scope of expression language supported by this property
	ExpressionLanguageScope string `json:"expressionLanguageScope,omitempty"`
	// The description of the expression language scope supported by this property
	ExpressionLanguageScopeDescription string `json:"expressionLanguageScopeDescription,omitempty"`
	// The name of the property key
	Name string `json:"name,omitempty"`
	// Whether or not  the property is required for the component
	Required bool `json:"required,omitempty"`
	ResourceDefinition *PropertyResourceDefinition `json:"resourceDefinition,omitempty"`
	// Whether or not  the value of the property is considered sensitive (e.g., passwords and keys)
	Sensitive bool `json:"sensitive,omitempty"`
	TypeProvidedByValue *DefinedType `json:"typeProvidedByValue,omitempty"`
	// A regular expression that can be used to validate the value of this property
	ValidRegex string `json:"validRegex,omitempty"`
	// Name of the validator used for this property descriptor
	Validator string `json:"validator,omitempty"`
}
