/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.1.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// Indicates if the component stores state
type Stateful struct {
	// Description of what information is being stored in the StateManager
	Description string `json:"description,omitempty"`
	// Indicates the Scope(s) associated with the State that is stored and retrieved
	Scopes []string `json:"scopes,omitempty"`
}
