/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.6.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The batch settings for data transmission.
type BatchSettingsDto struct {
	// Preferred number of flow files to include in a transaction.
	Count int32 `json:"count,omitempty"`
	// Preferred amount of time that a transaction should span.
	Duration string `json:"duration,omitempty"`
	// Preferred number of bytes to include in a transaction.
	Size string `json:"size,omitempty"`
}
