/*
 * NiFi Rest API
 *
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * API version: 1.23.2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nifi

type ProcessorDiagnosticsDto struct {
	// Information about the Processor for which the Diagnostic Report is generated
	Processor *ProcessorDto `json:"processor,omitempty"`
	// The Status for the Processor for which the Diagnostic Report is generated
	ProcessorStatus *ProcessorStatusDto `json:"processorStatus,omitempty"`
	// Diagnostic Information about all Controller Services that the Processor is referencing
	ReferencedControllerServices []ControllerServiceDiagnosticsDto `json:"referencedControllerServices,omitempty"`
	// Diagnostic Information about all incoming Connections
	IncomingConnections []ConnectionDiagnosticsDto `json:"incomingConnections,omitempty"`
	// Diagnostic Information about all outgoing Connections
	OutgoingConnections []ConnectionDiagnosticsDto `json:"outgoingConnections,omitempty"`
	// Diagnostic Information about the JVM and system-level diagnostics
	JvmDiagnostics *JvmDiagnosticsDto `json:"jvmDiagnostics,omitempty"`
	// Thread Dumps that were taken of the threads that are active in the Processor
	ThreadDumps []ThreadDumpDto `json:"threadDumps,omitempty"`
	// Information about the Controller Service's Class Loader
	ClassLoaderDiagnostics *ClassLoaderDiagnosticsDto `json:"classLoaderDiagnostics,omitempty"`
}
