/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.5.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The state.
type StateEntryDto struct {
	// The label for the node where the state originated.
	ClusterNodeAddress string `json:"clusterNodeAddress,omitempty"`
	// The identifier for the node where the state originated.
	ClusterNodeId string `json:"clusterNodeId,omitempty"`
	// The key for this state.
	Key string `json:"key,omitempty"`
	// The value for this state.
	Value string `json:"value,omitempty"`
}
