/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.5.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The status of the remote process group.
type RemoteProcessGroupStatusDto struct {
	AggregateSnapshot *RemoteProcessGroupStatusSnapshotDto `json:"aggregateSnapshot,omitempty"`
	// The unique ID of the process group that the Processor belongs to
	GroupId string `json:"groupId,omitempty"`
	// The unique ID of the Processor
	Id string `json:"id,omitempty"`
	// The name of the remote process group.
	Name string `json:"name,omitempty"`
	// A status snapshot for each node in the cluster. If the NiFi instance is a standalone instance, rather than a cluster, this may be null.
	NodeSnapshots []NodeRemoteProcessGroupStatusSnapshotDto `json:"nodeSnapshots,omitempty"`
	// The time the status for the process group was last refreshed.
	StatsLastRefreshed string `json:"statsLastRefreshed,omitempty"`
	// The URI of the target system.
	TargetUri string `json:"targetUri,omitempty"`
	// The transmission status of the remote process group.
	TransmissionStatus string `json:"transmissionStatus,omitempty"`
	// Indicates whether the component is valid, invalid, or still in the process of validating (i.e., it is unknown whether or not the component is valid)
	ValidationStatus string `json:"validationStatus,omitempty"`
}
