/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M4
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The destination of the connection.
type ConnectableComponent struct {
	// The id of the connectable component.
	Id string `json:"id,omitempty"`
	// The type of component the connectable is.
	Type_ string `json:"type,omitempty"`
	// The id of the group that the connectable component resides in
	GroupId string `json:"groupId,omitempty"`
	// The name of the connectable component
	Name string `json:"name,omitempty"`
	// The comments for the connectable component.
	Comments string `json:"comments,omitempty"`
	// The instance ID of an existing component that is described by this VersionedComponent, or null if this is not mapped to an instantiated component
	InstanceIdentifier string `json:"instanceIdentifier,omitempty"`
}
