/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M4
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type PeerDto struct {
	// The hostname of this peer.
	Hostname string `json:"hostname,omitempty"`
	// The port number of this peer.
	Port int32 `json:"port,omitempty"`
	// Returns if this peer connection is secure.
	Secure bool `json:"secure,omitempty"`
	// The number of flowFiles this peer holds.
	FlowFileCount int32 `json:"flowFileCount,omitempty"`
}
