/*
 * NiFi Rest API
 *
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * API version: 1.24.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nifi

type ComponentManifest struct {
	// Public interfaces defined in this bundle
	Apis []DefinedType `json:"apis,omitempty"`
	// Controller Services provided in this bundle
	ControllerServices []ControllerServiceDefinition `json:"controllerServices,omitempty"`
	// Processors provided in this bundle
	Processors []ProcessorDefinition `json:"processors,omitempty"`
	// Reporting Tasks provided in this bundle
	ReportingTasks []ReportingTaskDefinition `json:"reportingTasks,omitempty"`
}
