/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.9.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The list of secrets available from all secret providers.
type SecretDto struct {
	// A description of the secret.
	Description string `json:"description,omitempty"`
	// The fully qualified name of the secret, including the group name.
	FullyQualifiedName string `json:"fullyQualifiedName,omitempty"`
	// The name of the group this secret belongs to.
	GroupName string `json:"groupName,omitempty"`
	// The name of the secret.
	Name string `json:"name,omitempty"`
	// The identifier of the secret provider that manages this secret.
	ProviderId string `json:"providerId,omitempty"`
	// The name of the secret provider that manages this secret.
	ProviderName string `json:"providerName,omitempty"`
}
