/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.4.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The configuration analysis
type ConfigurationAnalysisDto struct {
	// The ID of the component
	ComponentId string `json:"componentId,omitempty"`
	// The configured properties for the component
	Properties map[string]string `json:"properties,omitempty"`
	// The attributes that are referenced by the properties, mapped to recently used values
	ReferencedAttributes map[string]string `json:"referencedAttributes,omitempty"`
	// Whether or not the component supports verification
	SupportsVerification bool `json:"supportsVerification,omitempty"`
}
