/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type RegisteredFlowSnapshotMetadata struct {
	BucketIdentifier string `json:"bucketIdentifier,omitempty"`
	FlowIdentifier string `json:"flowIdentifier,omitempty"`
	Version int32 `json:"version,omitempty"`
	Timestamp int64 `json:"timestamp,omitempty"`
	Author string `json:"author,omitempty"`
	Comments string `json:"comments,omitempty"`
}
