/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.3.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type ReplayLastEventResponseEntity struct {
	AggregateSnapshot *ReplayLastEventSnapshotDto `json:"aggregateSnapshot,omitempty"`
	// The UUID of the component whose last event should be replayed.
	ComponentId string `json:"componentId,omitempty"`
	// The node-wise results
	NodeSnapshots []NodeReplayLastEventSnapshotDto `json:"nodeSnapshots,omitempty"`
	// Which nodes were requested to replay their last provenance event.
	Nodes string `json:"nodes,omitempty"`
}
