/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.9.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// A list of ingress ports that are currently configured
type ListenPortDto struct {
	// Supported application protocols, if applicable
	ApplicationProtocols []string `json:"applicationProtocols,omitempty"`
	// The class type of the component providing the listen port
	ComponentClass string `json:"componentClass,omitempty"`
	// The id of the component providing the listen port
	ComponentId string `json:"componentId,omitempty"`
	// The name of the component providing the listen port
	ComponentName string `json:"componentName,omitempty"`
	// The type of component providing the listen port (e.g., Processor, ControllerService)
	ComponentType string `json:"componentType,omitempty"`
	// The id of the process group containing the component providing the listen port, if applicable
	ParentGroupId string `json:"parentGroupId,omitempty"`
	// The name of the process group containing the component providing the listen port, if applicable
	ParentGroupName string `json:"parentGroupName,omitempty"`
	// The name of the the listen port. Useful context for components that provide multiple ports.
	PortName string `json:"portName,omitempty"`
	// The ingress port number
	PortNumber int32 `json:"portNumber,omitempty"`
	// The ingress transport protocol (TCP or UDP)
	TransportProtocol string `json:"transportProtocol,omitempty"`
}
