/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The actions.
type ActionEntity struct {
	Id int32 `json:"id,omitempty"`
	// The timestamp of the action.
	Timestamp string `json:"timestamp,omitempty"`
	SourceId string `json:"sourceId,omitempty"`
	// Indicates whether the user can read a given resource.
	CanRead bool `json:"canRead,omitempty"`
	Action *ActionDto `json:"action,omitempty"`
}
