/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.7.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type ClearBulletinsForGroupRequestEntity struct {
	// Optional component IDs for which to clear bulletins. If not specified, all authorized descendant components will be used.
	Components []string `json:"components,omitempty"`
	// The timestamp from which to clear bulletins (inclusive). This field is required.
	FromTimestamp string `json:"fromTimestamp"`
	// The id of the ProcessGroup
	Id string `json:"id,omitempty"`
}
