/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The status of the connection.
type ConnectionStatusDto struct {
	// The ID of the connection
	Id string `json:"id,omitempty"`
	// The ID of the Process Group that the connection belongs to
	GroupId string `json:"groupId,omitempty"`
	// The name of the connection
	Name string `json:"name,omitempty"`
	// The timestamp of when the stats were last refreshed
	StatsLastRefreshed string `json:"statsLastRefreshed,omitempty"`
	// The ID of the source component
	SourceId string `json:"sourceId,omitempty"`
	// The name of the source component
	SourceName string `json:"sourceName,omitempty"`
	// The ID of the destination component
	DestinationId string `json:"destinationId,omitempty"`
	// The name of the destination component
	DestinationName string `json:"destinationName,omitempty"`
	AggregateSnapshot *ConnectionStatusSnapshotDto `json:"aggregateSnapshot,omitempty"`
	// A list of status snapshots for each node
	NodeSnapshots []NodeConnectionStatusSnapshotDto `json:"nodeSnapshots,omitempty"`
}
