/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The breadcrumb of the process group.
type FlowBreadcrumbEntity struct {
	// The id of this ancestor ProcessGroup.
	Id string `json:"id,omitempty"`
	Permissions *PermissionsDto `json:"permissions,omitempty"`
	// The current state of the Process Group, as it relates to the Versioned Flow
	VersionedFlowState string `json:"versionedFlowState,omitempty"`
	Breadcrumb *FlowBreadcrumbDto `json:"breadcrumb,omitempty"`
	ParentBreadcrumb *FlowBreadcrumbEntity `json:"parentBreadcrumb,omitempty"`
}
