/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M4
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type VersionedReportingTaskImportResponseEntity struct {
	// The reporting tasks created by the import
	ReportingTasks []ReportingTaskEntity `json:"reportingTasks,omitempty"`
	// The controller services created by the import
	ControllerServices []ControllerServiceEntity `json:"controllerServices,omitempty"`
}
