/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The provenance repository storage usage.
type StorageUsageDto struct {
	// The identifier of this storage location. The identifier will correspond to the identifier keyed in the storage configuration.
	Identifier string `json:"identifier,omitempty"`
	// Amount of free space.
	FreeSpace string `json:"freeSpace,omitempty"`
	// Amount of total space.
	TotalSpace string `json:"totalSpace,omitempty"`
	// Amount of used space.
	UsedSpace string `json:"usedSpace,omitempty"`
	// The number of bytes of free space.
	FreeSpaceBytes int64 `json:"freeSpaceBytes,omitempty"`
	// The number of bytes of total space.
	TotalSpaceBytes int64 `json:"totalSpaceBytes,omitempty"`
	// The number of bytes of used space.
	UsedSpaceBytes int64 `json:"usedSpaceBytes,omitempty"`
	// Utilization of this storage location.
	Utilization string `json:"utilization,omitempty"`
}
