/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.1.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// Permissions for specific component restrictions.
type ComponentRestrictionPermissionDto struct {
	Permissions *PermissionsDto `json:"permissions,omitempty"`
	RequiredPermission *RequiredPermissionDto `json:"requiredPermission,omitempty"`
}
