/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M4
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type FlowRegistryBucketEntity struct {
	Id string `json:"id,omitempty"`
	Bucket *FlowRegistryBucketDto `json:"bucket,omitempty"`
	Permissions *PermissionsDto `json:"permissions,omitempty"`
}
