/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type CountersDto struct {
	AggregateSnapshot *CountersSnapshotDto `json:"aggregateSnapshot,omitempty"`
	// A Counters snapshot for each node in the cluster. If the NiFi instance is a standalone instance, rather than a cluster, this may be null.
	NodeSnapshots []NodeCountersSnapshotDto `json:"nodeSnapshots,omitempty"`
}
