/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.5.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// A description of how to configure the Processor to perform the task described in the use case
type ProcessorConfiguration struct {
	// A description of how the Processor should be configured in order to accomplish the use case
	Configuration string `json:"configuration,omitempty"`
	// The fully qualified classname of the Processor that should be used to accomplish the use case
	ProcessorClassName string `json:"processorClassName,omitempty"`
}
