/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.1.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi
import (
	"time"
)

// The nifi, os, java, and build version information
type VersionInfoDto struct {
	// Build branch
	BuildBranch string `json:"buildBranch,omitempty"`
	// Build revision or commit hash
	BuildRevision string `json:"buildRevision,omitempty"`
	// Build tag
	BuildTag string `json:"buildTag,omitempty"`
	// Build timestamp
	BuildTimestamp time.Time `json:"buildTimestamp,omitempty"`
	// Java JVM vendor
	JavaVendor string `json:"javaVendor,omitempty"`
	// Java version
	JavaVersion string `json:"javaVersion,omitempty"`
	// The version of this NiFi.
	NiFiVersion string `json:"niFiVersion,omitempty"`
	// Host operating system architecture
	OsArchitecture string `json:"osArchitecture,omitempty"`
	// Host operating system name
	OsName string `json:"osName,omitempty"`
	// Host operating system version
	OsVersion string `json:"osVersion,omitempty"`
}
