/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.4.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The nodes in the lineage.
type ProvenanceNodeDto struct {
	// The uuid of the childrent flowfiles of the provenance event.
	ChildUuids []string `json:"childUuids,omitempty"`
	// The identifier of the node that this event/flowfile originated from.
	ClusterNodeIdentifier string `json:"clusterNodeIdentifier,omitempty"`
	// If the type is EVENT, this is the type of event.
	EventType string `json:"eventType,omitempty"`
	// The uuid of the flowfile associated with the provenance event.
	FlowFileUuid string `json:"flowFileUuid,omitempty"`
	// The id of the node.
	Id string `json:"id,omitempty"`
	// The timestamp of the node in milliseconds.
	Millis int64 `json:"millis,omitempty"`
	// The uuid of the parent flowfiles of the provenance event.
	ParentUuids []string `json:"parentUuids,omitempty"`
	// The timestamp of the node formatted.
	Timestamp string `json:"timestamp,omitempty"`
	// The type of the node.
	Type_ string `json:"type,omitempty"`
}
