/*
 * NiFi Rest API
 *
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * API version: 1.17.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nifi

type JvmControllerDiagnosticsSnapshotDto struct {
	// Whether or not this node is primary node
	PrimaryNode bool `json:"primaryNode,omitempty"`
	// Whether or not this node is cluster coordinator
	ClusterCoordinator bool `json:"clusterCoordinator,omitempty"`
	// The maximum number of timer-driven threads
	MaxTimerDrivenThreads int32 `json:"maxTimerDrivenThreads,omitempty"`
	// The maximum number of event-driven threads
	MaxEventDrivenThreads int32 `json:"maxEventDrivenThreads,omitempty"`
}
