/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.4.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The list of differences for each component in the flow that is not the same between the two flows
type ComponentDifferenceDto struct {
	// The ID of the component
	ComponentId string `json:"componentId,omitempty"`
	// The name of the component
	ComponentName string `json:"componentName,omitempty"`
	// The type of component
	ComponentType string `json:"componentType,omitempty"`
	// The differences in the component between the two flows
	Differences []DifferenceDto `json:"differences,omitempty"`
	// The ID of the Process Group that the component belongs to
	ProcessGroupId string `json:"processGroupId,omitempty"`
}
