/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.3.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type PortStatusEntity struct {
	// Indicates whether the user can read a given resource.
	CanRead bool `json:"canRead,omitempty"`
	PortStatus *PortStatusDto `json:"portStatus,omitempty"`
}
