/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.4.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type StartVersionControlRequestEntity struct {
	// Acknowledges that this node is disconnected to allow for mutable requests to proceed.
	DisconnectedNodeAcknowledged bool `json:"disconnectedNodeAcknowledged,omitempty"`
	ProcessGroupRevision *RevisionDto `json:"processGroupRevision,omitempty"`
	VersionedFlow *VersionedFlowDto `json:"versionedFlow,omitempty"`
}
