/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M4
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The Version Control information
type VersionControlInformationDto struct {
	// The ID of the Process Group that is under version control
	GroupId string `json:"groupId,omitempty"`
	// The ID of the registry that the flow is stored in
	RegistryId string `json:"registryId,omitempty"`
	// The name of the registry that the flow is stored in
	RegistryName string `json:"registryName,omitempty"`
	// The ID of the branch that the flow is stored in
	Branch string `json:"branch,omitempty"`
	// The ID of the bucket that the flow is stored in
	BucketId string `json:"bucketId,omitempty"`
	// The name of the bucket that the flow is stored in
	BucketName string `json:"bucketName,omitempty"`
	// The ID of the flow
	FlowId string `json:"flowId,omitempty"`
	// The name of the flow
	FlowName string `json:"flowName,omitempty"`
	// The description of the flow
	FlowDescription string `json:"flowDescription,omitempty"`
	// The version of the flow
	Version interface{} `json:"version,omitempty"`
	// The storage location
	StorageLocation string `json:"storageLocation,omitempty"`
	// The current state of the Process Group, as it relates to the Versioned Flow
	State string `json:"state,omitempty"`
	// Explanation of why the group is in the specified state
	StateExplanation string `json:"stateExplanation,omitempty"`
}
