/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type DocumentedTypeDto struct {
	// The fully qualified name of the type.
	Type_ string `json:"type,omitempty"`
	Bundle *BundleDto `json:"bundle,omitempty"`
	// If this type represents a ControllerService, this lists the APIs it implements.
	ControllerServiceApis []ControllerServiceApiDto `json:"controllerServiceApis,omitempty"`
	// The description of the type.
	Description string `json:"description,omitempty"`
	// Whether this type is restricted.
	Restricted bool `json:"restricted,omitempty"`
	// The optional description of why the usage of this component is restricted.
	UsageRestriction string `json:"usageRestriction,omitempty"`
	// An optional collection of explicit restrictions. If specified, these explicit restrictions will be enfored.
	ExplicitRestrictions []ExplicitRestrictionDto `json:"explicitRestrictions,omitempty"`
	// The description of why the usage of this component is restricted.
	DeprecationReason string `json:"deprecationReason,omitempty"`
	// The tags associated with this type.
	Tags []string `json:"tags,omitempty"`
}
