/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// If the property identifies a controller service this returns the bundle of the type, null otherwise.
type BundleDto struct {
	// The group of the bundle.
	Group string `json:"group,omitempty"`
	// The artifact of the bundle.
	Artifact string `json:"artifact,omitempty"`
	// The version of the bundle.
	Version string `json:"version,omitempty"`
}
