/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.5.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The bulletins for this component.
type BulletinEntity struct {
	Bulletin *BulletinDto `json:"bulletin,omitempty"`
	// Indicates whether the user can read a given resource.
	CanRead bool `json:"canRead,omitempty"`
	GroupId string `json:"groupId,omitempty"`
	Id int64 `json:"id,omitempty"`
	NodeAddress string `json:"nodeAddress,omitempty"`
	SourceId string `json:"sourceId,omitempty"`
	// When this bulletin was generated.
	Timestamp string `json:"timestamp,omitempty"`
}
