/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M4
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type VersionedFlowSnapshotMetadataEntity struct {
	VersionedFlowSnapshotMetadata *RegisteredFlowSnapshotMetadata `json:"versionedFlowSnapshotMetadata,omitempty"`
	// The ID of the Registry that this flow belongs to
	RegistryId string `json:"registryId,omitempty"`
}
