/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.5.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type VersionedReportingTaskSnapshot struct {
	// The controller services
	ControllerServices []VersionedControllerService `json:"controllerServices,omitempty"`
	// The reporting tasks
	ReportingTasks []VersionedReportingTask `json:"reportingTasks,omitempty"`
}
