/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.1.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type HistoryDto struct {
	// The actions.
	Actions []ActionEntity `json:"actions,omitempty"`
	// The timestamp when the report was generated.
	LastRefreshed string `json:"lastRefreshed,omitempty"`
	// The number of number of actions that matched the search criteria..
	Total int32 `json:"total,omitempty"`
}
