/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.5.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The mime types this Content Viewer supports.
type SupportedMimeTypesDto struct {
	// The display name of the mime types.
	DisplayName string `json:"displayName,omitempty"`
	// The mime types this Content Viewer supports.
	MimeTypes []string `json:"mimeTypes,omitempty"`
}
