/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// A list of the allowable values for the property
type PropertyAllowableValue struct {
	// The internal value
	Value string `json:"value,omitempty"`
	// The display name of the value, if different from the internal value
	DisplayName string `json:"displayName,omitempty"`
	// The description of the value, e.g., the behavior it produces.
	Description string `json:"description,omitempty"`
}
