/*
 * NiFi Rest API
 *
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * API version: 1.21.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nifi

type SchedulingDefaults struct {
	// The name of the default scheduling strategy
	DefaultSchedulingStrategy string `json:"defaultSchedulingStrategy,omitempty"`
	// The default scheduling period in milliseconds
	DefaultSchedulingPeriodMillis int64 `json:"defaultSchedulingPeriodMillis,omitempty"`
	// The default penalization period in milliseconds
	PenalizationPeriodMillis int64 `json:"penalizationPeriodMillis,omitempty"`
	// The default yield duration in milliseconds
	YieldDurationMillis int64 `json:"yieldDurationMillis,omitempty"`
	// The default run duration in nano-seconds
	DefaultRunDurationNanos int64 `json:"defaultRunDurationNanos,omitempty"`
	// The default concurrent tasks
	DefaultMaxConcurrentTasks string `json:"defaultMaxConcurrentTasks,omitempty"`
	// The default concurrent tasks for each scheduling strategy
	DefaultConcurrentTasksBySchedulingStrategy map[string]int32 `json:"defaultConcurrentTasksBySchedulingStrategy,omitempty"`
	// The default scheduling period for each scheduling strategy
	DefaultSchedulingPeriodsBySchedulingStrategy map[string]string `json:"defaultSchedulingPeriodsBySchedulingStrategy,omitempty"`
}
