/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.9.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The list of configuration step configurations for this Connector.
type ConfigurationStepConfigurationDto struct {
	// The description of the configuration step.
	ConfigurationStepDescription string `json:"configurationStepDescription,omitempty"`
	// The name of the configuration step.
	ConfigurationStepName string `json:"configurationStepName,omitempty"`
	// The dependencies that this configuration step has on other configuration steps' properties.
	Dependencies []ConfigurationStepDependencyDto `json:"dependencies,omitempty"`
	// Whether extended documentation is available for this configuration step.
	Documented bool `json:"documented,omitempty"`
	// The list of property group configurations for this configuration step.
	PropertyGroupConfigurations []PropertyGroupConfigurationDto `json:"propertyGroupConfigurations,omitempty"`
}
