/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.1.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The versioned flow
type VersionedFlowDto struct {
	// The action being performed
	Action string `json:"action,omitempty"`
	// The branch where the flow is stored
	Branch string `json:"branch,omitempty"`
	// The ID of the bucket where the flow is stored
	BucketId string `json:"bucketId,omitempty"`
	// Comments for the changeset
	Comments string `json:"comments,omitempty"`
	// A description of the flow
	Description string `json:"description,omitempty"`
	// The ID of the flow
	FlowId string `json:"flowId,omitempty"`
	// The name of the flow
	FlowName string `json:"flowName,omitempty"`
	// The ID of the registry that the flow is tracked to
	RegistryId string `json:"registryId,omitempty"`
}
