/*
 * NiFi Rest API
 *
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * API version: 1.23.2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nifi

type ClassLoaderDiagnosticsDto struct {
	// Information about the Bundle that the ClassLoader belongs to, if any
	Bundle *BundleDto `json:"bundle,omitempty"`
	// A ClassLoaderDiagnosticsDTO that provides information about the parent ClassLoader
	ParentClassLoader *ClassLoaderDiagnosticsDto `json:"parentClassLoader,omitempty"`
}
