/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.6.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type PasteResponseEntity struct {
	Flow *FlowDto `json:"flow,omitempty"`
	Revision *RevisionDto `json:"revision,omitempty"`
}
