/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.9.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The dependencies this property has on other properties.
type ConnectorPropertyDependencyDto struct {
	// The values of the dependent property that must be set for this property to be applicable.
	DependentValues []string `json:"dependentValues,omitempty"`
	// The name of the property that this property depends on.
	PropertyName string `json:"propertyName,omitempty"`
}
