/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The size of the queue
type QueueSizeDto struct {
	// The size of objects in a queue.
	ByteCount int64 `json:"byteCount,omitempty"`
	// The count of objects in a queue.
	ObjectCount int32 `json:"objectCount,omitempty"`
}
