/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.5.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The garbage collection details.
type GarbageCollectionDto struct {
	// The number of times garbage collection has run.
	CollectionCount int64 `json:"collectionCount,omitempty"`
	// The total number of milliseconds spent garbage collecting.
	CollectionMillis int64 `json:"collectionMillis,omitempty"`
	// The total amount of time spent garbage collecting.
	CollectionTime string `json:"collectionTime,omitempty"`
	// The name of the garbage collector.
	Name string `json:"name,omitempty"`
}
