/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type FlowAnalysisRuleDto struct {
	// The id of the component.
	Id string `json:"id,omitempty"`
	// The ID of the corresponding component that is under version control
	VersionedComponentId string `json:"versionedComponentId,omitempty"`
	// The id of parent process group of this component if applicable.
	ParentGroupId string `json:"parentGroupId,omitempty"`
	Position *PositionDto `json:"position,omitempty"`
	// The name of the flow analysis rule.
	Name string `json:"name,omitempty"`
	// The fully qualified type of the flow analysis rule.
	Type_ string `json:"type,omitempty"`
	Bundle *BundleDto `json:"bundle,omitempty"`
	// The state of the flow analysis rule.
	State string `json:"state,omitempty"`
	// The comments of the flow analysis rule.
	Comments string `json:"comments,omitempty"`
	// Whether the flow analysis rule persists state.
	PersistsState bool `json:"persistsState,omitempty"`
	// Whether the flow analysis rule requires elevated privileges.
	Restricted bool `json:"restricted,omitempty"`
	// Whether the flow analysis rule has been deprecated.
	Deprecated bool `json:"deprecated,omitempty"`
	// Whether the flow analysis rule has multiple versions available.
	MultipleVersionsAvailable bool `json:"multipleVersionsAvailable,omitempty"`
	// Whether the flow analysis rule supports sensitive dynamic properties.
	SupportsSensitiveDynamicProperties bool `json:"supportsSensitiveDynamicProperties,omitempty"`
	// Enforcement Policy.
	EnforcementPolicy string `json:"enforcementPolicy,omitempty"`
	// The properties of the flow analysis rule.
	Properties map[string]string `json:"properties,omitempty"`
	// The descriptors for the flow analysis rules properties.
	Descriptors map[string]PropertyDescriptorDto `json:"descriptors,omitempty"`
	// Set of sensitive dynamic property names
	SensitiveDynamicPropertyNames []string `json:"sensitiveDynamicPropertyNames,omitempty"`
	// Gets the validation errors from the flow analysis rule. These validation errors represent the problems with the flow analysis rule that must be resolved before it can be scheduled to run.
	ValidationErrors []string `json:"validationErrors,omitempty"`
	// Indicates whether the Flow Analysis Rule is valid, invalid, or still in the process of validating (i.e., it is unknown whether or not the Flow Analysis Rule is valid)
	ValidationStatus string `json:"validationStatus,omitempty"`
	// Whether the underlying extension is missing.
	ExtensionMissing bool `json:"extensionMissing,omitempty"`
}
