/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.6.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type ClusterDto struct {
	// The timestamp the report was generated.
	Generated string `json:"generated,omitempty"`
	// The collection of nodes that are part of the cluster.
	Nodes []NodeDto `json:"nodes,omitempty"`
}
