/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.5.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type BulletinDto struct {
	// The category of this bulletin.
	Category string `json:"category,omitempty"`
	// The group id of the source component.
	GroupId string `json:"groupId,omitempty"`
	// The id of the bulletin.
	Id int64 `json:"id,omitempty"`
	// The level of the bulletin.
	Level string `json:"level,omitempty"`
	// The bulletin message.
	Message string `json:"message,omitempty"`
	// If clustered, the address of the node from which the bulletin originated.
	NodeAddress string `json:"nodeAddress,omitempty"`
	// The id of the source component.
	SourceId string `json:"sourceId,omitempty"`
	// The name of the source component.
	SourceName string `json:"sourceName,omitempty"`
	// The type of the source component
	SourceType string `json:"sourceType,omitempty"`
	// When this bulletin was generated.
	Timestamp string `json:"timestamp,omitempty"`
}
