/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.9.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The connector status snapshot from the node.
type ConnectorStatusSnapshotDto struct {
	// The number of active threads for the connector.
	ActiveThreadCount int32 `json:"activeThreadCount,omitempty"`
	// The number of bytes queued in this connector's managed process group.
	BytesQueued int64 `json:"bytesQueued,omitempty"`
	// The number of bytes read by processors in this connector's managed process group.
	BytesRead int64 `json:"bytesRead,omitempty"`
	// The number of bytes received by this connector's managed process group.
	BytesReceived int64 `json:"bytesReceived,omitempty"`
	// The number of bytes sent by this connector's managed process group.
	BytesSent int64 `json:"bytesSent,omitempty"`
	// The number of bytes written by processors in this connector's managed process group.
	BytesWritten int64 `json:"bytesWritten,omitempty"`
	// The number of FlowFiles queued in this connector's managed process group.
	FlowFilesQueued int32 `json:"flowFilesQueued,omitempty"`
	// The number of FlowFiles received by this connector's managed process group.
	FlowFilesReceived int32 `json:"flowFilesReceived,omitempty"`
	// The number of FlowFiles sent by this connector's managed process group.
	FlowFilesSent int32 `json:"flowFilesSent,omitempty"`
	// The id of the parent process group to which the connector belongs.
	GroupId string `json:"groupId,omitempty"`
	// The id of the connector.
	Id string `json:"id,omitempty"`
	// Whether or not the connector is currently idle (no FlowFiles queued and no FlowFiles processed recently).
	Idle bool `json:"idle,omitempty"`
	// A human-readable representation of how long the connector has been idle, or null if the connector is not idle.
	IdleDuration string `json:"idleDuration,omitempty"`
	// The number of milliseconds the connector has been idle, or null if the connector is not idle.
	IdleDurationMillis int64 `json:"idleDurationMillis,omitempty"`
	// The name of the connector.
	Name string `json:"name,omitempty"`
	ProcessingPerformanceStatus *ProcessingPerformanceStatusDto `json:"processingPerformanceStatus,omitempty"`
	// The count/size of queued data, pretty-printed.
	Queued string `json:"queued,omitempty"`
	// The count of queued FlowFiles, pretty-printed.
	QueuedCount string `json:"queuedCount,omitempty"`
	// The size of queued data, pretty-printed.
	QueuedSize string `json:"queuedSize,omitempty"`
	// The number of bytes read, pretty-printed.
	Read string `json:"read,omitempty"`
	// The count/size of data that has been received by this connector, pretty-printed.
	Received string `json:"received,omitempty"`
	// The run status of the connector.
	RunStatus string `json:"runStatus,omitempty"`
	// The count/size of data that has been sent by this connector, pretty-printed.
	Sent string `json:"sent,omitempty"`
	// The type of the connector.
	Type_ string `json:"type,omitempty"`
	// The number of bytes written, pretty-printed.
	Written string `json:"written,omitempty"`
}
