/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.3.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The local state for this component.
type StateMapDto struct {
	// The scope of this StateMap.
	Scope string `json:"scope,omitempty"`
	// The state.
	State []StateEntryDto `json:"state,omitempty"`
	// The total number of state entries. When the state map is lengthy, only of portion of the entries are returned.
	TotalEntryCount int32 `json:"totalEntryCount,omitempty"`
}
