/*
 * NiFi Rest API
 *
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * API version: 1.23.2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nifi

type ReplayLastEventSnapshotDto struct {
	// The IDs of the events that were successfully replayed
	EventsReplayed []int64 `json:"eventsReplayed,omitempty"`
	// If unable to replay an event, specifies why the event could not be replayed
	FailureExplanation string `json:"failureExplanation,omitempty"`
	// Whether or not an event was available. This may not be populated if there was a failure.
	EventAvailable bool `json:"eventAvailable,omitempty"`
}
