/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.6.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The Remote Process Groups
type VersionedRemoteProcessGroup struct {
	// The user-supplied comments for the component
	Comments string `json:"comments,omitempty"`
	// The time period used for the timeout when communicating with the target.
	CommunicationsTimeout string `json:"communicationsTimeout,omitempty"`
	ComponentType string `json:"componentType,omitempty"`
	// The ID of the Process Group that this component belongs to
	GroupIdentifier string `json:"groupIdentifier,omitempty"`
	// The component's unique identifier
	Identifier string `json:"identifier,omitempty"`
	// A Set of Input Ports that can be connected to, in order to send data to the remote NiFi instance
	InputPorts []VersionedRemoteGroupPort `json:"inputPorts,omitempty"`
	// The instance ID of an existing component that is described by this VersionedComponent, or null if this is not mapped to an instantiated component
	InstanceIdentifier string `json:"instanceIdentifier,omitempty"`
	// The local network interface to send/receive data. If not specified, any local address is used. If clustered, all nodes must have an interface with this identifier.
	LocalNetworkInterface string `json:"localNetworkInterface,omitempty"`
	// The component's name
	Name string `json:"name,omitempty"`
	// A Set of Output Ports that can be connected to, in order to pull data from the remote NiFi instance
	OutputPorts []VersionedRemoteGroupPort `json:"outputPorts,omitempty"`
	Position *Position `json:"position,omitempty"`
	ProxyHost string `json:"proxyHost,omitempty"`
	ProxyPassword string `json:"proxyPassword,omitempty"`
	ProxyPort int32 `json:"proxyPort,omitempty"`
	ProxyUser string `json:"proxyUser,omitempty"`
	// The target URIs of the remote process group. If target uris is not set but target uri is set, then returns the single target uri. If neither target uris nor target uri is set, then returns null.
	TargetUris string `json:"targetUris,omitempty"`
	// The Transport Protocol that is used for Site-to-Site communications. Possible returned values: RAW, HTTP.
	TransportProtocol string `json:"transportProtocol,omitempty"`
	// When yielding, this amount of time must elapse before the remote process group is scheduled again.
	YieldDuration string `json:"yieldDuration,omitempty"`
}
