/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.1.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type ProcessGroupReplaceRequestEntity struct {
	ProcessGroupRevision *RevisionDto `json:"processGroupRevision,omitempty"`
	Request *ProcessGroupReplaceRequestDto `json:"request,omitempty"`
	VersionedFlowSnapshot *RegisteredFlowSnapshot `json:"versionedFlowSnapshot,omitempty"`
}
