/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.4.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The component state.
type ComponentStateDto struct {
	ClusterState *StateMapDto `json:"clusterState,omitempty"`
	// The component identifier.
	ComponentId string `json:"componentId,omitempty"`
	LocalState *StateMapDto `json:"localState,omitempty"`
	// Description of the state this component persists.
	StateDescription string `json:"stateDescription,omitempty"`
}
