/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type FlowComparisonEntity struct {
	// The list of differences for each component in the flow that is not the same between the two flows
	ComponentDifferences []ComponentDifferenceDto `json:"componentDifferences,omitempty"`
}
