/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.4.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type VersionedReportingTaskImportRequestEntity struct {
	// The disconnected node acknowledged flag
	DisconnectedNodeAcknowledged bool `json:"disconnectedNodeAcknowledged,omitempty"`
	ReportingTaskSnapshot *VersionedReportingTaskSnapshot `json:"reportingTaskSnapshot,omitempty"`
}
