/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.3.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type ProcessorStatusDto struct {
	AggregateSnapshot *ProcessorStatusSnapshotDto `json:"aggregateSnapshot,omitempty"`
	// The unique ID of the process group that the Processor belongs to
	GroupId string `json:"groupId,omitempty"`
	// The unique ID of the Processor
	Id string `json:"id,omitempty"`
	// The name of the Processor
	Name string `json:"name,omitempty"`
	// A status snapshot for each node in the cluster. If the NiFi instance is a standalone instance, rather than a cluster, this may be null.
	NodeSnapshots []NodeProcessorStatusSnapshotDto `json:"nodeSnapshots,omitempty"`
	// The run status of the Processor
	RunStatus string `json:"runStatus,omitempty"`
	// The timestamp of when the stats were last refreshed
	StatsLastRefreshed string `json:"statsLastRefreshed,omitempty"`
	// The type of the Processor
	Type_ string `json:"type,omitempty"`
}
