/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.9.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

type VerifyConnectorConfigStepRequestEntity struct {
	Request *VerifyConnectorConfigStepRequestDto `json:"request,omitempty"`
}
