/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.4.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The assets that are referenced by this parameter
type VersionedAsset struct {
	// The identifier of the asset
	Identifier string `json:"identifier,omitempty"`
	// The name of the asset
	Name string `json:"name,omitempty"`
}
