/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.3.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// The search terms used to perform the search.
type ProvenanceSearchValueDto struct {
	// Query for all except for search value.
	Inverse bool `json:"inverse,omitempty"`
	// The search value.
	Value string `json:"value,omitempty"`
}
