/*
 * NiFi Rest API
 *
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * API version: 1.18.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nifi

type RegisteredFlowSnapshot struct {
	SnapshotMetadata *RegisteredFlowSnapshotMetadata `json:"snapshotMetadata,omitempty"`
	Flow *RegisteredFlow `json:"flow,omitempty"`
	Bucket *FlowRegistryBucket `json:"bucket,omitempty"`
	FlowContents *VersionedProcessGroup `json:"flowContents,omitempty"`
	ExternalControllerServices map[string]ExternalControllerServiceReference `json:"externalControllerServices,omitempty"`
	ParameterContexts map[string]VersionedParameterContext `json:"parameterContexts,omitempty"`
	FlowEncodingVersion string `json:"flowEncodingVersion,omitempty"`
	ParameterProviders map[string]ParameterProviderReference `json:"parameterProviders,omitempty"`
	Latest bool `json:"latest,omitempty"`
}
