/*
 * Apache NiFi REST API
 *
 * REST API definition for Apache NiFi web services
 *
 * API version: 2.0.0-M2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nifi

// Describes the dynamic properties supported by this component
type DynamicProperty struct {
	// The description of the dynamic property name
	Name string `json:"name,omitempty"`
	// The description of the dynamic property value
	Value string `json:"value,omitempty"`
	// The description of the dynamic property
	Description string `json:"description,omitempty"`
	// The scope of the expression language support
	ExpressionLanguageScope string `json:"expressionLanguageScope,omitempty"`
}
