/*
 * Apache NiFi Registry REST API
 *
 * The REST API provides an interface to a registry with operations for saving, versioning, reading NiFi flows and components.
 *
 * API version: 0.8.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package registry

type VersionedPropertyDescriptor struct {
	// The name of the property
	Name string `json:"name,omitempty"`
	// The display name of the property
	DisplayName string `json:"displayName,omitempty"`
	// Whether or not the property provides the identifier of a Controller Service
	IdentifiesControllerService bool `json:"identifiesControllerService,omitempty"`
	// Whether or not the property is considered sensitive
	Sensitive bool `json:"sensitive,omitempty"`
}
