/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.5.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The Output Ports
type VersionedPort struct {
	// Whether or not this port allows remote access for site-to-site
	AllowRemoteAccess bool `json:"allowRemoteAccess,omitempty"`
	// The user-supplied comments for the component
	Comments string `json:"comments,omitempty"`
	ComponentType string `json:"componentType,omitempty"`
	// The number of tasks that should be concurrently scheduled for the port.
	ConcurrentlySchedulableTaskCount int32 `json:"concurrentlySchedulableTaskCount,omitempty"`
	// The ID of the Process Group that this component belongs to
	GroupIdentifier string `json:"groupIdentifier,omitempty"`
	// The component's unique identifier
	Identifier string `json:"identifier,omitempty"`
	// The instance ID of an existing component that is described by this VersionedComponent, or null if this is not mapped to an instantiated component
	InstanceIdentifier string `json:"instanceIdentifier,omitempty"`
	// The component's name
	Name string `json:"name,omitempty"`
	// Specifies how the Port should function
	PortFunction string `json:"portFunction,omitempty"`
	Position *Position `json:"position,omitempty"`
	// The scheduled state of the component
	ScheduledState string `json:"scheduledState,omitempty"`
	// The type of port.
	Type_ string `json:"type,omitempty"`
}
