/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.0.0-M4
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The optional resource definition
type ResourceDefinition struct {
	// The cardinality of the resource definition
	Cardinality string `json:"cardinality,omitempty"`
	// The types of resources
	ResourceTypes []string `json:"resourceTypes,omitempty"`
}
