/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.3.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

type BundleVersion struct {
	Bucket *Bucket `json:"bucket,omitempty"`
	Bundle *Bundle `json:"bundle,omitempty"`
	// The set of other bundle versions that this version is dependent on
	Dependencies []BundleVersionDependency `json:"dependencies,omitempty"`
	Filename string `json:"filename,omitempty"`
	Link *Link `json:"link,omitempty"`
	VersionMetadata *BundleVersionMetadata `json:"versionMetadata"`
}
