/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.3.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

type ExtensionRepoVersion struct {
	DownloadLink *Link `json:"downloadLink,omitempty"`
	ExtensionsLink *Link `json:"extensionsLink,omitempty"`
	Sha256Link *Link `json:"sha256Link,omitempty"`
	// Indicates if the client supplied a SHA-256 when uploading this version of the extension bundle.
	Sha256Supplied bool `json:"sha256Supplied,omitempty"`
}
