/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.3.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The list of changes related to this component between the 2 versions.
type ComponentDifference struct {
	// The description of the change.
	ChangeDescription string `json:"changeDescription,omitempty"`
	// The key to the difference.
	DifferenceType string `json:"differenceType,omitempty"`
	// The description of the change type.
	DifferenceTypeDescription string `json:"differenceTypeDescription,omitempty"`
	// The earlier value from the difference.
	ValueA string `json:"valueA,omitempty"`
	// The newer value from the difference.
	ValueB string `json:"valueB,omitempty"`
}
