/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.4.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// Zero or more documented use cases for how the extension may be used
type UseCase struct {
	Configuration string `json:"configuration,omitempty"`
	Description string `json:"description,omitempty"`
	InputRequirement string `json:"inputRequirement,omitempty"`
	Keywords []string `json:"keywords,omitempty"`
	Notes string `json:"notes,omitempty"`
}
