/*
 * Apache NiFi Registry REST API
 *
 * The REST API provides an interface to a registry with operations for saving, versioning, reading NiFi flows and components.
 *
 * API version: 0.8.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package registry

type DynamicProperty struct {
	// The description of the dynamic property name
	Name string `json:"name,omitempty"`
	// The description of the dynamic property value
	Value string `json:"value,omitempty"`
	// The description of the dynamic property
	Description string `json:"description,omitempty"`
	// The scope of the expression language support
	ExpressionLanguageScope string `json:"expressionLanguageScope,omitempty"`
	// Whether or not expression language is supported
	ExpressionLanguageSupported bool `json:"expressionLanguageSupported,omitempty"`
}
