/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.3.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The restrictions of the extension
type Restricted struct {
	// The general restriction for the extension, or null if only specific restrictions exist
	GeneralRestrictionExplanation string `json:"generalRestrictionExplanation,omitempty"`
	// The specific restrictions
	Restrictions []Restriction `json:"restrictions,omitempty"`
}
