/*
 * Apache NiFi Registry REST API
 *
 * The REST API provides an interface to a registry with operations for saving, versioning, reading NiFi flows and components.
 *
 * API version: 0.8.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package registry

type Property struct {
	// The name of the property
	Name string `json:"name,omitempty"`
	// The display name
	DisplayName string `json:"displayName,omitempty"`
	// The description
	Description string `json:"description,omitempty"`
	// The default value
	DefaultValue string `json:"defaultValue,omitempty"`
	// The controller service required by this property, or null if none is required
	ControllerServiceDefinition *ControllerServiceDefinition `json:"controllerServiceDefinition,omitempty"`
	// The allowable values for this property
	AllowableValues []AllowableValue `json:"allowableValues,omitempty"`
	// Whether or not the property is required
	Required bool `json:"required,omitempty"`
	// Whether or not the property is sensitive
	Sensitive bool `json:"sensitive,omitempty"`
	// Whether or not expression language is supported
	ExpressionLanguageSupported bool `json:"expressionLanguageSupported,omitempty"`
	// The scope of expression language support
	ExpressionLanguageScope string `json:"expressionLanguageScope,omitempty"`
	// Whether or not the processor dynamically modifies the classpath
	DynamicallyModifiesClasspath bool `json:"dynamicallyModifiesClasspath,omitempty"`
	// Whether or not the processor is dynamic
	Dynamic bool `json:"dynamic,omitempty"`
}
