/*
 * Apache NiFi Registry REST API
 *
 * The REST API provides an interface to a registry with operations for saving, versioning, reading NiFi flows and components.
 *
 * API version: 1.23.2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package registry

type VersionedResourceDefinition struct {
	// The cardinality of the resource
	Cardinality string `json:"cardinality,omitempty"`
	// The types of resource that the Property Descriptor is allowed to reference
	ResourceTypes []string `json:"resourceTypes,omitempty"`
}
