/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.0.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry
import (
	"time"
)

type FormDataContentDisposition struct {
	Type_ string `json:"type,omitempty"`
	Parameters map[string]string `json:"parameters,omitempty"`
	FileName string `json:"fileName,omitempty"`
	CreationDate time.Time `json:"creationDate,omitempty"`
	ModificationDate time.Time `json:"modificationDate,omitempty"`
	ReadDate time.Time `json:"readDate,omitempty"`
	Size int64 `json:"size,omitempty"`
	Name string `json:"name,omitempty"`
}
