/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.8.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// Returns the Listen Port Definition for the port this property specifies, if applicable
type VersionedListenPortDefinition struct {
	// The application protocol(s) that the listen port could support (if any)
	ApplicationProtocols []string `json:"applicationProtocols,omitempty"`
	// The transport protocol used by the listen port
	TransportProtocol string `json:"transportProtocol,omitempty"`
}
