/*
 * Apache NiFi Registry REST API
 *
 * The REST API provides an interface to a registry with operations for saving, versioning, reading NiFi flows and components.
 *
 * API version: 0.8.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package registry

type Permissions struct {
	// Indicates whether the user can read a given resource.
	CanRead bool `json:"canRead,omitempty"`
	// Indicates whether the user can write a given resource.
	CanWrite bool `json:"canWrite,omitempty"`
	// Indicates whether the user can delete a given resource.
	CanDelete bool `json:"canDelete,omitempty"`
}
