/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.9.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The property groups in this configuration step
type ConnectorPropertyGroup struct {
	// The description of the property group
	Description string `json:"description,omitempty"`
	// The name of the property group
	Name string `json:"name,omitempty"`
	// The properties in this group
	Properties []ConnectorProperty `json:"properties,omitempty"`
}
