/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.0.0-M2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The flow this snapshot is for
type VersionedFlow struct {
	Link *Link `json:"link,omitempty"`
	// An ID to uniquely identify this object.
	Identifier string `json:"identifier"`
	// The name of the item.
	Name string `json:"name"`
	// A description of the item.
	Description string `json:"description,omitempty"`
	// The identifier of the bucket this items belongs to. This cannot be changed after the item is created.
	BucketIdentifier string `json:"bucketIdentifier"`
	// The name of the bucket this items belongs to.
	BucketName string `json:"bucketName,omitempty"`
	// The timestamp of when the item was created, as milliseconds since epoch.
	CreatedTimestamp int64 `json:"createdTimestamp,omitempty"`
	// The timestamp of when the item was last modified, as milliseconds since epoch.
	ModifiedTimestamp int64 `json:"modifiedTimestamp,omitempty"`
	// The type of item.
	Type_ string `json:"type"`
	Permissions *Permissions `json:"permissions,omitempty"`
	// The number of versions of this flow.
	VersionCount int64 `json:"versionCount,omitempty"`
	Revision *RevisionInfo `json:"revision,omitempty"`
}
