/*
 * Apache NiFi Registry REST API
 *
 * The REST API provides an interface to a registry with operations for saving, versioning, reading NiFi flows and components.
 *
 * API version: 0.8.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package registry

type ComponentDifference struct {
	// The earlier value from the difference.
	ValueA string `json:"valueA,omitempty"`
	// The newer value from the difference.
	ValueB string `json:"valueB,omitempty"`
	// The description of the change.
	ChangeDescription string `json:"changeDescription,omitempty"`
	// The key to the difference.
	DifferenceType string `json:"differenceType,omitempty"`
	// The description of the change type.
	DifferenceTypeDescription string `json:"differenceTypeDescription,omitempty"`
}
