/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.0.0-M4
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

type TagCount struct {
	// The tag label
	Tag string `json:"tag,omitempty"`
	// The number of occurrences of the given tag
	Count int32 `json:"count,omitempty"`
}
