/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.1.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The resource considerations of the extension
type SystemResourceConsideration struct {
	// The description of how the resource is affected
	Description string `json:"description,omitempty"`
	// The resource to consider
	Resource string `json:"resource,omitempty"`
}
