/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.4.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The parameter contexts referenced by process groups in the flow contents. The mapping is from the name of the context to the context instance, and it is expected that any context in this map is referenced by at least one process group in this flow.
type VersionedParameterContext struct {
	// The user-supplied comments for the component
	Comments string `json:"comments,omitempty"`
	ComponentType string `json:"componentType,omitempty"`
	// The description of the parameter context
	Description string `json:"description,omitempty"`
	// The ID of the Process Group that this component belongs to
	GroupIdentifier string `json:"groupIdentifier,omitempty"`
	// The component's unique identifier
	Identifier string `json:"identifier,omitempty"`
	// The names of additional parameter contexts from which to inherit parameters
	InheritedParameterContexts []string `json:"inheritedParameterContexts,omitempty"`
	// The instance ID of an existing component that is described by this VersionedComponent, or null if this is not mapped to an instantiated component
	InstanceIdentifier string `json:"instanceIdentifier,omitempty"`
	// The component's name
	Name string `json:"name,omitempty"`
	// The corresponding parameter group name fetched from the parameter provider, if applicable
	ParameterGroupName string `json:"parameterGroupName,omitempty"`
	// The identifier of an optional parameter provider
	ParameterProvider string `json:"parameterProvider,omitempty"`
	// The parameters in the context
	Parameters []VersionedParameter `json:"parameters,omitempty"`
	Position *Position `json:"position,omitempty"`
	// True if the parameter provider is set and the context should receive updates when its parameters are next fetched
	Synchronized bool `json:"synchronized,omitempty"`
}
