/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.0.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

type VersionedFlowDifference struct {
	// The id of the bucket that the flow is stored in.
	BucketId string `json:"bucketId,omitempty"`
	// The id of the flow that is being examined.
	FlowId string `json:"flowId,omitempty"`
	// The earlier version from the diff operation.
	VersionA int32 `json:"versionA,omitempty"`
	// The latter version from the diff operation.
	VersionB int32 `json:"versionB,omitempty"`
	ComponentDifferenceGroups []ComponentDifferenceGroup `json:"componentDifferenceGroups,omitempty"`
}
