/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.0.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The default schedule for a processor reporting task
type DefaultSchedule struct {
	// The default scheduling strategy
	Strategy string `json:"strategy,omitempty"`
	// The default scheduling period
	Period string `json:"period,omitempty"`
	// The default concurrent tasks
	ConcurrentTasks string `json:"concurrentTasks,omitempty"`
}
