/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.0.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The relationships of the extension
type Relationship struct {
	// The name of the relationship
	Name string `json:"name,omitempty"`
	// The description of the relationship
	Description string `json:"description,omitempty"`
	// Whether or not the relationship is auto-terminated by default
	AutoTerminated bool `json:"autoTerminated,omitempty"`
}
