/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.3.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// An WebLink to this entity.
type Link struct {
	Params map[string]string `json:"params,omitempty"`
	Rel string `json:"rel,omitempty"`
	Rels []string `json:"rels,omitempty"`
	Title string `json:"title,omitempty"`
	Type_ string `json:"type,omitempty"`
	Uri string `json:"uri,omitempty"`
	UriBuilder *UriBuilder `json:"uriBuilder,omitempty"`
}
