/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.9.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The optional listen port definition
type ListenPortDefinition struct {
	// The application protocols that this listen port could support (if any)
	ApplicationProtocols []string `json:"applicationProtocols,omitempty"`
	// The transport protocol used by this listen port
	TransportProtocol string `json:"transportProtocol,omitempty"`
}
