/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.9.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The properties that this property depends on
type ConnectorPropertyDependency struct {
	// The values of the dependent property that enable this property
	DependentValues []string `json:"dependentValues,omitempty"`
	// The name of the property that this property depends on
	PropertyName string `json:"propertyName,omitempty"`
}
