/*
 * Apache NiFi Registry REST API
 *
 * The REST API provides an interface to a registry with operations for saving, versioning, reading NiFi flows and components.
 *
 * API version: 0.8.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package registry

type ResourcePermissions struct {
	// The access that the current user has to the top level /buckets resource of this NiFi Registry (i.e., access to all buckets)
	Buckets *Permissions `json:"buckets,omitempty"`
	// The access that the current user has to the top level /tenants resource of this NiFi Registry
	Tenants *Permissions `json:"tenants,omitempty"`
	// The access that the current user has to the top level /policies resource of this NiFi Registry
	Policies *Permissions `json:"policies,omitempty"`
	// The access that the current user has to the top level /proxy resource of this NiFi Registry
	Proxy *Permissions `json:"proxy,omitempty"`
	// The access that the current user has to any top level resources (a logical 'OR' of all other values)
	AnyTopLevelResource *Permissions `json:"anyTopLevelResource,omitempty"`
}
