/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.9.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The dependencies that this step has on other steps
type ConfigurationStepDependency struct {
	// The values of the dependent property that enable this step
	DependentValues []string `json:"dependentValues,omitempty"`
	// The name of the property within the step that this step depends on
	PropertyName string `json:"propertyName,omitempty"`
	// The name of the step that this step depends on
	StepName string `json:"stepName,omitempty"`
}
