/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.0.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The metadata for the extensions
type ExtensionMetadata struct {
	Link *Link `json:"link,omitempty"`
	// The name of the extension
	Name string `json:"name,omitempty"`
	// The display name of the extension
	DisplayName string `json:"displayName,omitempty"`
	// The type of the extension
	Type_ string `json:"type,omitempty"`
	// The description of the extension
	Description string `json:"description,omitempty"`
	DeprecationNotice *DeprecationNotice `json:"deprecationNotice,omitempty"`
	// The tags of the extension
	Tags []string `json:"tags,omitempty"`
	Restricted *Restricted `json:"restricted,omitempty"`
	// The service APIs provided by the extension
	ProvidedServiceAPIs []ProvidedServiceApi `json:"providedServiceAPIs,omitempty"`
	BundleInfo *BundleInfo `json:"bundleInfo,omitempty"`
	// Whether or not the extension has additional detail documentation
	HasAdditionalDetails bool `json:"hasAdditionalDetails,omitempty"`
	LinkDocs *Link `json:"linkDocs,omitempty"`
}
