/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.0.0-M2
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

type ExtensionMetadataContainer struct {
	// The number of extensions in the response
	NumResults int32 `json:"numResults,omitempty"`
	FilterParams *ExtensionFilterParams `json:"filterParams,omitempty"`
	// The metadata for the extensions
	Extensions []ExtensionMetadata `json:"extensions,omitempty"`
}
