/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.4.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The build information about this version
type BuildInfo struct {
	// The branch used to build the version of the bundle
	BuildBranch string `json:"buildBranch,omitempty"`
	// The flags used to build the version of the bundle
	BuildFlags string `json:"buildFlags,omitempty"`
	// The revision used to build the version of the bundle
	BuildRevision string `json:"buildRevision,omitempty"`
	// The tag used to build the version of the bundle
	BuildTag string `json:"buildTag,omitempty"`
	// The tool used to build the version of the bundle
	BuildTool string `json:"buildTool,omitempty"`
	// The timestamp the version of the bundle was built
	Built int64 `json:"built,omitempty"`
	// The identity of the user that performed the build
	BuiltBy string `json:"builtBy,omitempty"`
}
