/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.5.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The service APIs provided by the extension
type ProvidedServiceApi struct {
	// The artifact id of the service API being provided
	ArtifactId string `json:"artifactId,omitempty"`
	// The class name of the service API being provided
	ClassName string `json:"className,omitempty"`
	// The group id of the service API being provided
	GroupId string `json:"groupId,omitempty"`
	// The version of the service API being provided
	Version string `json:"version,omitempty"`
}
