/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.1.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

type AccessPolicy struct {
	// The action associated with this access policy.
	Action string `json:"action,omitempty"`
	// Indicates if this access policy is configurable, based on which Authorizer has been configured to manage it.
	Configurable bool `json:"configurable,omitempty"`
	// The id of the policy. Set by server at creation time.
	Identifier string `json:"identifier,omitempty"`
	// The resource for this access policy.
	Resource string `json:"resource,omitempty"`
	Revision *RevisionInfo `json:"revision,omitempty"`
	// The set of user group IDs associated with this access policy.
	UserGroups []Tenant `json:"userGroups,omitempty"`
	// The set of user IDs associated with this access policy.
	Users []Tenant `json:"users,omitempty"`
}
