/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.0.0-M4
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

type ExtensionRepoGroup struct {
	Link *Link `json:"link,omitempty"`
	// The bucket name
	BucketName string `json:"bucketName,omitempty"`
	// The group id
	GroupId string `json:"groupId,omitempty"`
}
