/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.5.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The dynamic properties of the extension
type DynamicProperty struct {
	// The description of the dynamic property
	Description string `json:"description,omitempty"`
	// The scope of the expression language support
	ExpressionLanguageScope string `json:"expressionLanguageScope,omitempty"`
	// Whether or not expression language is supported
	ExpressionLanguageSupported bool `json:"expressionLanguageSupported,omitempty"`
	// The description of the dynamic property name
	Name string `json:"name,omitempty"`
	// The description of the dynamic property value
	Value string `json:"value,omitempty"`
}
