/*
 * Apache NiFi Registry REST API
 *
 * The REST API provides an interface to a registry with operations for saving, versioning, reading NiFi flows and components.
 *
 * API version: 0.8.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package registry

type SystemResourceConsideration struct {
	// The resource to consider
	Resource string `json:"resource,omitempty"`
	// The description of how the resource is affected
	Description string `json:"description,omitempty"`
}
