/*
 * Apache NiFi Registry REST API
 *
 * The REST API provides an interface to a registry with operations for saving, versioning, reading NiFi flows and components.
 *
 * API version: 0.8.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package registry

type Restricted struct {
	// The general restriction for the extension, or null if only specific restrictions exist
	GeneralRestrictionExplanation string `json:"generalRestrictionExplanation,omitempty"`
	// The specific restrictions
	Restrictions []Restriction `json:"restrictions,omitempty"`
}
