/*
 * Apache NiFi Registry REST API
 *
 * The REST API provides an interface to a registry with operations for saving, versioning, reading NiFi flows and components.
 *
 * API version: 0.8.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package registry

type ExtensionRepoGroup struct {
	// An WebLink to this entity.
	Link *JaxbLink `json:"link,omitempty"`
	// The bucket name
	BucketName string `json:"bucketName,omitempty"`
	// The group id
	GroupId string `json:"groupId,omitempty"`
}
