/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.1.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

type BundlesBundleTypeBody struct {
	File *FormDataContentDisposition `json:"file,omitempty"`
	Sha256 string `json:"sha256,omitempty"`
}
