/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.0.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

type VersionedFlowSnapshot struct {
	SnapshotMetadata *VersionedFlowSnapshotMetadata `json:"snapshotMetadata"`
	FlowContents *VersionedProcessGroup `json:"flowContents"`
	// The information about controller services that exist outside this versioned flow, but are referenced by components within the versioned flow.
	ExternalControllerServices map[string]ExternalControllerServiceReference `json:"externalControllerServices,omitempty"`
	// Contains basic information about parameter providers referenced in the versioned flow.
	ParameterProviders map[string]ParameterProviderReference `json:"parameterProviders,omitempty"`
	// The parameter contexts referenced by process groups in the flow contents. The mapping is from the name of the context to the context instance, and it is expected that any context in this map is referenced by at least one process group in this flow.
	ParameterContexts map[string]VersionedParameterContext `json:"parameterContexts,omitempty"`
	// The optional encoding version of the flow contents.
	FlowEncodingVersion string `json:"flowEncodingVersion,omitempty"`
	Flow *VersionedFlow `json:"flow,omitempty"`
	Bucket *Bucket `json:"bucket,omitempty"`
	Latest bool `json:"latest,omitempty"`
}
