/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.0.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// Lists the APIs this Controller Service implements.
type ControllerServiceApi struct {
	// The fully qualified name of the service interface.
	Type_ string `json:"type,omitempty"`
	Bundle *Bundle `json:"bundle,omitempty"`
}
