/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.0.0-M4
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The bucket where the flow is located
type Bucket struct {
	Link *Link `json:"link,omitempty"`
	// An ID to uniquely identify this object.
	Identifier string `json:"identifier"`
	// The name of the bucket.
	Name string `json:"name"`
	// The timestamp of when the bucket was first created. This is set by the server at creation time.
	CreatedTimestamp int64 `json:"createdTimestamp,omitempty"`
	// A description of the bucket.
	Description string `json:"description,omitempty"`
	// Indicates if this bucket allows the same version of an extension bundle to be redeployed and thus overwrite the existing artifact. By default this is false.
	AllowBundleRedeploy bool `json:"allowBundleRedeploy,omitempty"`
	// Indicates if this bucket allows read access to unauthenticated anonymous users
	AllowPublicRead bool `json:"allowPublicRead,omitempty"`
	Permissions *Permissions `json:"permissions,omitempty"`
	Revision *RevisionInfo `json:"revision,omitempty"`
}
