/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.0.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// Contains basic information about parameter providers referenced in the versioned flow.
type ParameterProviderReference struct {
	// The identifier of the parameter provider
	Identifier string `json:"identifier,omitempty"`
	// The name of the parameter provider
	Name string `json:"name,omitempty"`
	// The fully qualified name of the parameter provider class.
	Type_ string `json:"type,omitempty"`
	Bundle *Bundle `json:"bundle,omitempty"`
}
