/*
 * Apache NiFi Registry REST API
 *
 * REST API definition for Apache NiFi Registry web services
 *
 * API version: 2.1.0
 * Contact: dev@nifi.apache.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package registry

// The default settings for a processor
type DefaultSettings struct {
	// The default bulletin level
	BulletinLevel string `json:"bulletinLevel,omitempty"`
	// The default penalty duration
	PenaltyDuration string `json:"penaltyDuration,omitempty"`
	// The default yield duration
	YieldDuration string `json:"yieldDuration,omitempty"`
}
